name: Code quality
on:
  push:
    branches: [main]
    paths:
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"
      - ".pre-commit-config.yaml"
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"
      - ".pre-commit-config.yaml"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python and uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync --all-groups --frozen

      - name: Run pre-commit checks
        run: uv run pre-commit run --all-files --verbose
