name: Documentation
on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "uv.lock"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Git credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Set up Python and uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync --all-groups --frozen

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ hashFiles('uv.lock') }}
          path: .cache
          restore-keys: mkdocs-material-

      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force
